version: '3.8'

services:
  mysql:
    image: mysql
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  nestjs-app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file: .env
    depends_on:
     mysql:
        condition: service_healthy
